site_name: Pyxems Documentation

nav:
  - Home: index.md
  - CLI Ref: cli-ref.md

theme:
  name: material
  features:
    - navigation.indexes

plugins:
- search
- cyclopts
- mkdocstrings:
    docstring_style: google
- api-autonav:
    modules: ['src/pyxems']
