name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  python-version: "3.12"

permissions:
  contents: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
        with:
          args: 'check'        
      - uses: astral-sh/ruff-action@v3
        with:
          args: 'format --check'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Run Ty
        run: |
            uvx ty check

  doc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.python-version }}
          cache: 'pip'
      - run: |
          pip install --upgrade pip
          uv sync --only-group doc
      - name: Build Doc
        run: |
          uv run mkdocs build

  testing:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    needs: [check-format, doc-build]

    steps:
    - uses: actions/checkout@v6
    - name: Install openEMS for linux
      if: ${{runner.os != 'Windows' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y openems
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.python-version }}
    - name: Install Dependencies
      run: |
        uv tree
        uv sync --group dev
    - name: Test with Pytest
      run: |
        uv run poe test -rxXs
    - name: Store reports
      if: failure()
      uses: actions/upload-artifact@v6
      with:
        name: reports-${{ matrix.os }}
        path: |
          tmp/
          pytest.log
          .coverage
