name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  python-version: "3.12"

permissions:
  contents: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
        with:
          args: 'check'        
      - uses: astral-sh/ruff-action@v3
        with:
          args: 'format --check'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Run Ty
        run: |
            uv sync --all-extras
            uvx ty check
  
  doc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Build Doc
        run: |
          uv sync --all-extras --group doc
          uv run mkdocs build


  testing:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    needs: [check-format, doc-test]

    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
      if: ${{runner.os != 'Windows' }}
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Install openEMS for linux
      if: ${{runner.os != 'Windows' }}
      run: |
        nix-channel --list
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
        nix-channel --update
        nix-env -iA nixpkgs.openems
        which openEMS
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.python-version }}
    - name: Install Dependencies
      run: |
        uv tree
        uv sync --group dev --all-extras
    - name: Test with Pytest
      run: |
        uv run pytest -rxXs --basetemp=tmp 
    - name: Store reports
      uses: actions/upload-artifact@v6
      with:
        name: reports-${{ matrix.os }}
        path: |
          tmp/
          pytest.log
